name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  docs:
    name: Documentation Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings
      - run: pip install vpic-api
      - run: mkdocs gh-deploy --force