name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  docs:
    name: Documentation Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Publish docs to Github Pages
        shell: bash
        run: poetry run mkdocs gh-deploy --force
